### ISSUE TITLE
Album links fail on home (needs Link.To...)

### ISSUE THREAD

**Issue by mangiove** [2sic/app-blueimp#1]
Hi, clicking on a thumbnail of an album in the lists it gives a page with the following error:

**404 Not Found
The requested Url does not return any valid content.
Administrators
Change this message by configuring a specific 404 Error Page or Url for this website.**

Here is the test link:
**http://www.msgweb.it//mid/412/album/apericena-1**

Btw really nice app-update. I just tryed it out on a test environment.
Can you provide just some instruction to upgrade the 2.0 version? Trying to install this on a portal where there is the older version just fail because they use the same directory name.

Thanks you

**Comment by iJungleboy** [comment]
I see the bug - it's a dnn url issue with the home page. So atm this will only work on any page except for home. We'll try to fix asap...

**Comment by iJungleboy** [comment]
@raphael-m pls connect it to use the @Link.To linking, which corrects the home-special-url issue.

**Comment by mangiove** [comment]
@iJungleboy  ok got it thanks: `@Link.To(parameters: "album=" + @Content.Path)` this href would resolve the issue
